---
title: "Test"
date: 2020-07-20
---

title: Your awesome title
author: Jess
email: j@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My description :D 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
